# Name of website
title: Ryan's Website

# Your name to show in the footer
author: Ryan

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "转码的小菜菜"
  Contact: "waiting ~"
  Author's home: "https://ryan-leey.github.io/"

#################
# --- Logo --- #
#################

# avatar: "/assets/img/avatar-icon.png"

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "ryan_lee@stu.pku.edu.cn"
  github: https://ryan-leey.github.io/

###########################
# --- General options --- #
###########################



#####################################
# --- Colours / background image --- #
#####################################

page-col: "#F5F5F5"
text-col: "#333333"
link-col: "#4A90E2"
hover-col: "#368AD2"
navbar-col: "#FFFFFF"
navbar-text-col: "#404040"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#333333"
footer-hover-col: "#368AD2"

#site-css:
#  - "/assets/css/custom-styles.css"

#################
# --- Misc --- #
#################

date_format: "%B %-d, %Y"

#################################################################################
# --- You don't need to touch anything below here --- #
#################################################################################

timezone: "Asia/Shanghai"
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom CSS
site-css:
  - "/assets/css/custom-styles.css"
